# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "36d8bf04-dbff-4458-aa00-e77993fdda21"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  build_android_app(task: "assembleRelease")

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "835d54a4706563d782475ef15c5a5e0c62751415",
    build_secret: "33b32cd6e7f8fa573b984c54102b15182624f1dc3dc8bb389c015a53b60ac16f"
  )
end
